name: kebabbo_flutter
description: Kebbabbo Flutter version.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  supabase_flutter: ^2.5.6
  image_picker: ^1.0.5
  flutter_dotenv: ^5.0.3
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.0.20
  geolocator: ^12.0.0
  flutter_map_marker_popup: ^7.0.0
  webview_flutter: ^4.0.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0

  postgrest: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
