name: kebabbo_flutter
description: Kebbabbo Flutter version.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  english_words: ^4.0.0
  provider: ^6.0.0
  supabase_flutter: ^2.5.6
  image_picker: ^1.0.5
  flutter_dotenv: ^5.0.3
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.0.20
  geolocator: ^13.0.1
  flutter_map_marker_popup: ^7.0.0
  webview_flutter: ^4.0.7
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.14.1
  fl_chart: ^0.69.0
  google_sign_in: ^6.2.2
  postgrest: any
  flutter_map_cancellable_tile_provider: ^3.0.2
  fuzzy: ^0.5.1
  flutter_svg: ^2.0.10+1
  timeago: ^3.0.2
  file_picker: ^8.1.3
  image: ^4.3.0
  http: ^1.2.2
  flip_card: ^0.7.0
  crypto: ^3.0.6
  flutter_rating_bar: ^4.0.1
  awesome_dialog: ^3.2.1
  flutter_animate: ^4.5.0
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - packages/font_awesome_flutter/fonts/fa-brands-400.ttf
