// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-3zpLn8iCKwN_LHWiW7OH6IL7zjZYGLI',
    appId: '1:1072333391081:web:755c7e7478f11522f2dc78',
    messagingSenderId: '1072333391081',
    projectId: 'kebabbo',
    authDomain: 'kebabbo.firebaseapp.com',
    storageBucket: 'kebabbo.firebasestorage.app',
    measurementId: 'G-XMXNKQ2YVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSppGBgoNec1Eu3MrAw4CkS4eFzOIhxq8',
    appId: '1:1072333391081:android:f3fd344f4f874f52f2dc78',
    messagingSenderId: '1072333391081',
    projectId: 'kebabbo',
    storageBucket: 'kebabbo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNHnFyXtYPvxBqcQ0oYHb6CxdbnqPs8Mw',
    appId: '1:1072333391081:ios:7e14fadb08836f4df2dc78',
    messagingSenderId: '1072333391081',
    projectId: 'kebabbo',
    storageBucket: 'kebabbo.firebasestorage.app',
    androidClientId: '1072333391081-7nqbpab7ollm7p149v7qieiuln1a8uph.apps.googleusercontent.com',
    iosBundleId: 'com.canny.kebabbo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNHnFyXtYPvxBqcQ0oYHb6CxdbnqPs8Mw',
    appId: '1:1072333391081:ios:7e14fadb08836f4df2dc78',
    messagingSenderId: '1072333391081',
    projectId: 'kebabbo',
    storageBucket: 'kebabbo.firebasestorage.app',
    androidClientId: '1072333391081-7nqbpab7ollm7p149v7qieiuln1a8uph.apps.googleusercontent.com',
    iosBundleId: 'com.canny.kebabbo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-3zpLn8iCKwN_LHWiW7OH6IL7zjZYGLI',
    appId: '1:1072333391081:web:742e5ee84180c687f2dc78',
    messagingSenderId: '1072333391081',
    projectId: 'kebabbo',
    authDomain: 'kebabbo.firebaseapp.com',
    storageBucket: 'kebabbo.firebasestorage.app',
    measurementId: 'G-QBWPH0TZM2',
  );
}
